### ISSUE TITLE
Period not works, never resetting

### ISSUE THREAD

**Issue by markitosgv** [jaytaph/RateLimitBundle#29] opened 2016-03-08 10:30 UTC
Hi,

Im trying this bundle but i notice that never resetRate, i´ve been searching in code an method resetRate is never called.

Whats wrong?

**Comment by s4brown** [comment] 2016-03-17 22:26
I'm having a similar issue. Were you able to figure this out? I'm using the doctrine_cache if it makes any difference.

**Comment by markitosgv** [comment] 2016-03-18 12:25
If you seek here:
https://github.com/jaytaph/RateLimitBundle/search?utf8=%E2%9C%93&q=resetRate

Any method call reset action. Then i don't know if anyone is working with this bundle.

**Comment by s4brown** [comment] 2016-03-18 15:40
I fixed this here https://github.com/s4brown/RateLimitBundle/tree/resetrate and submitted a pull request.

**Comment by jaytaph** [comment] 2016-03-22 09:01
@s4brown Thanks for the PR.. I will check it today and see if this solves @markitosgv problem.

**Comment by jaytaph** [comment] 2016-03-25 08:04
@markitosgv @s4brown I've taken a look about this issue. It seemed very strange that the most basic feature of a rate limiter wasn't working. 

The reason that resetRate isn't called is because resetting is taken care of by the initial storage engine redis. Here, we add an expiry to the rate limit, so it will expire after a certain time so we don't have to call reset ourselves (https://github.com/jaytaph/RateLimitBundle/blob/master/Service/Storage/Redis.php#L48). The same will happen in the other storage engines. Can you tell me which doctrine cache backend you are using? 

However, I think it should not be left solely on the storage backend (maybe some backends do not have a TTL for instance), so I think the PR is a valid one,. I have to check to see how we can incorporate that without issues.

**Comment by markitosgv** [comment] 2016-03-25 09:08
It's the most basic feature of this bundle, it seems strange for me too.
I'm not using doctrine

**Comment by jaytaph** [comment] 2016-03-25 09:10
@markitosgv which one are you using?

**Comment by markitosgv** [comment] 2016-03-25 09:15
Redis :)

**Comment by jaytaph** [comment] 2016-03-25 09:17
ok.. that is very strange..  I'll take a look to see if I can find an issue with the expiry..

**Comment by s4brown** [comment] 2016-03-25 16:49
Ah, I see now how you were doing that. resetRate shouldn't have to be called if the storage engine expires it. I am using the basic doctrine cache and it also supports setting the lifetime/expiry of the cache entry but it also doesn't seem to work.

**Comment by jaytaph** [comment] 2016-03-29 10:14
I've checked the bundle, but I cannot find anything that seems to be wrong. However, i haven't tried with the basic doctrine cache, but that too has its own expiry.

The `resetRate` method is normally needed for explicitly removing a rate limit. Normally it is indeed controlled by an expiry option on a cache. However, this means that any cache system MUST have expiry functionality. The given PR will actually call `resetRate` after the rate has expired. If a cache does not support expiration, this will manually clear the limit, otherwise the cache has already done it before, so i think it's a good PR that I will accept.

It might solve the problem, but it does not explain why the problem is there to begin with, which bothers me a bit to be honest :(

**Comment by satanasdiabolo** [comment] 2016-03-31 09:59
When this PR will be merged ?

I had some keys that did not expires (I dunno why) and the rate limit was always reach. I had to remove manually in my storage expired data :-(

**Comment by jaytaph** [comment] 2016-03-31 10:13
It has been released together as version 1.7.0.

If anyone can provide me with a (reproducible) version of this issue, I'm grateful for that as I cannot reproduce the issue myself.

**Closed by jaytaph** 2016-03-31 10:13 UTC
